version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_APP_4321
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_URL=${APPWRITE_URL}
